name: Run Unit Tests
on: pull_request
env:
  DATABASE_URL: ${{ unit_test_environments.DATABASE_URL }}
  CLIENT_URL: ${{ unit_test_environments.CLIENT_URL }}
  EMAIL_NAME_SERVICE: ${{ unit_test_environments.EMAIL_NAME_SERVICE }}
  EMAIL_PASSWORD_SERVICE: ${{ unit_test_environments.EMAIL_PASSWORD_SERVICE }}
  GOOGLE_CLIENT_ID: ${{ unit_test_environments.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ unit_test_environments.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CALL_BACK: ${{ unit_test_environments.GOOGLE_CALL_BACK }}
  GOOGLE_CLOUD_PROJECT_ID: ${{ unit_test_environments.GOOGLE_CLOUD_PROJECT_ID }}
  GOOGLE_CLOUD_PRIVATE_KEY_ID: ${{ unit_test_environments.GOOGLE_CLOUD_PRIVATE_KEY_ID }}
  GOOGLE_CLOUD_PRIVATE_KEY_ENCODE: ${{ unit_test_environments.GOOGLE_CLOUD_PRIVATE_KEY_ENCODE }}
  GOOGLE_CLOUD_CLIENT_EMAIL: ${{ unit_test_environments.GOOGLE_CLOUD_CLIENT_EMAIL }}
  GOOGLE_CLOUD_STORAGE_MEDIA_BUCKET: ${{ unit_test_environments.GOOGLE_CLOUD_STORAGE_MEDIA_BUCKET }}
  GOOGLE_CLOUD_CLIENT_ID: ${{ unit_test_environments.GOOGLE_CLOUD_CLIENT_ID }}
  JWT_ACCESS_SECRET: ${{ unit_test_environments.JWT_ACCESS_SECRET }}
  JWT_REFRESH_SECRET: ${{ unit_test_environments.JWT_REFRESH_SECRET }}
  STUDENT_JWT_ACCESS_SECRET: ${{ unit_test_environments.STUDENT_JWT_ACCESS_SECRET }}
  STUDENT_JWT_REFRESH_SECRET: ${{ unit_test_environments.STUDENT_JWT_REFRESH_SECRET }}
  STRIPE_SECRET_KEY: ${{ unit_test_environments.STRIPE_SECRET_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test
