name: Run Unit Tests
on: pull_request
env:
  DATABASE_URL: ${{ env.DATABASE_URL }}
  CLIENT_URL: ${{ env.CLIENT_URL }}
  EMAIL_NAME_SERVICE: ${{ env.EMAIL_NAME_SERVICE }}
  EMAIL_PASSWORD_SERVICE: ${{ env.EMAIL_PASSWORD_SERVICE }}
  GOOGLE_CLIENT_ID: ${{ env.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ env.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CALL_BACK: ${{ env.GOOGLE_CALL_BACK }}
  GOOGLE_CLOUD_PROJECT_ID: ${{ env.GOOGLE_CLOUD_PROJECT_ID }}
  GOOGLE_CLOUD_PRIVATE_KEY_ID: ${{ env.GOOGLE_CLOUD_PRIVATE_KEY_ID }}
  GOOGLE_CLOUD_PRIVATE_KEY_ENCODE: ${{ env.GOOGLE_CLOUD_PRIVATE_KEY_ENCODE }}
  GOOGLE_CLOUD_CLIENT_EMAIL: ${{ env.GOOGLE_CLOUD_CLIENT_EMAIL }}
  GOOGLE_CLOUD_STORAGE_MEDIA_BUCKET: ${{ env.GOOGLE_CLOUD_STORAGE_MEDIA_BUCKET }}
  GOOGLE_CLOUD_CLIENT_ID: ${{ env.GOOGLE_CLOUD_CLIENT_ID }}
  JWT_ACCESS_SECRET: ${{ env.JWT_ACCESS_SECRET }}
  JWT_REFRESH_SECRET: ${{ env.JWT_REFRESH_SECRET }}
  STUDENT_JWT_ACCESS_SECRET: ${{ env.STUDENT_JWT_ACCESS_SECRET }}
  STUDENT_JWT_REFRESH_SECRET: ${{ env.STUDENT_JWT_REFRESH_SECRET }}
  STRIPE_SECRET_KEY: ${{ env.STRIPE_SECRET_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check ENV
        run: echo "MY STORAGE NAME IS $GOOGLE_CLOUD_STORAGE_MEDIA_BUCKET"
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test
